KERNEL_POLITICALINFORMATION_MODEL = 'shell.PoliticalInformation'
KERNEL_DEPARTMENT_MODEL = 'shell.Department'
KERNEL_CENTRE_MODEL = 'shell.Centre'
KERNEL_DEGREE_MODEL = 'shell.Degree'
KERNEL_STUDENT_MODEL = 'shell.Student'
KERNEL_FACULTYMEMBER_MODEL = 'shell.FacultyMember'
KERNEL_MAINTAINER_MODEL = 'shell.Maintainer'
