# Generated by Django 2.2.3 on 2019-09-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shell', '0002_facultymember_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicalinformation',
            name='reservation_category',
            field=models.CharField(choices=[('gen', 'General'), ('sc', 'Scheduled Caste'), ('st', 'Scheduled Tribe'), ('obc', 'Other Backward Classes'), ('army', 'Army Veteran'), ('navy', 'Navy Veteran'), ('air-for', 'Air-Force Veteran'), ('qip', 'Qualified Institutional Participant'), ('iccr', 'Indian Council for Cultural Relations'), ('itec', 'Indian Technical and Economic Cooperation Programme'), ('for', 'Foreigner'), ('spon', 'Sponsored'), ('gen-pd', 'General(Physically Disabled)'), ('gen-ews', 'General(Economically Backward Section)'), ('sc-pd', 'Scheduled Caste(Physically Disabled)'), ('st-pd', 'Scheduled Tribe(Physically Disabled)'), ('drdo', 'Defence Research and Development Organisation'), ('other', 'Other')], max_length=7),
        ),
    ]
