# Generated by Django 3.0.3 on 2020-12-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shell', '0005_auto_20200110_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintainer',
            name='designation',
            field=models.CharField(choices=[('web', 'Webmaster'), ('pra', 'Project associate'), ('pro', 'Project leader'), ('coo', 'Coordinator'), ('adv', 'Technical adviser'), ('eco', 'Emeritus coordinator')], max_length=3),
        ),
    ]
