# Generated by Django 3.2.8 on 2022-02-06 14:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.KERNEL_PERSON_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('shell', '0007_auto_20211130_0216'),
    ]

    run_before = [
        ('kernel', '0007_jointfaculty_jointfacultymembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre',
            name='code',
            field=models.CharField(choices=[('ahec', 'Alternate Hydro Energy Centre'), ('cnt', 'Centre for Nanotechnology'), ('caids', 'Centre for Aritificial Intelligence and Data Science'), ('cecqc', 'Continuing Education Centre and QIP Centre'), ('mfsdsai', 'Mehta Family School of Data Science and Artificial Intelligence'), ('cedmm', 'Centre of Excellence in Disaster Mitigation and Management'), ('cts', 'Centre for Transportation Systems'), ('chs', 'Centre for Himalayan Studies'), ('ceudm', 'Centre of Excellence in Urban Design and Management'), ('mgcl', 'Mahatma Gandhi Central Library'), ('cec', 'Continuing Education Centre'), ('icc', 'Institute Computer Centre'), ('iic', 'Institute Instrumentation Centre'), ('iprc', 'Intellectual Property Rights Cell'), ('etc', 'Education Technology Cell'), ('ih', 'Institute Hospital'), ('tides', 'Tides Incubation Centre')], max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='degree',
            name='code',
            field=models.CharField(choices=[('btech', 'B.Tech. - Bachelor of Technology'), ('idd', 'Int. M.Tech. - Integrated Dual Degree'), ('bsc', 'B.Sc. - Bachelor of Science'), ('barch', 'B.Arch. - Bachelor of Architecture'), ('imsc', 'Int. M.Sc. - Integrated Master of Science'), ('imt', 'Int. M.Tech - Integrated Master of Technology'), ('bsms', 'BS-MS - Bachelor of Science - Master of Science'), ('mtech', 'M.Tech. - Master of Technology'), ('msc', 'M.Sc. - Master of Science'), ('march', 'M.Arch. - Master of Architecture'), ('murp', 'M.U.R.P - Master of Urban and Regional Planning'), ('pgdip', 'P.G. Dip. - Post-graduate Diploma'), ('mba', 'M.B.A. - Master of Business Administration'), ('mca', 'M.C.A. - Master of Computer Applications'), ('mdes', 'Master of Design'), ('mim', 'Master in Innovation Management'), ('phd', 'Ph.D. - Doctor of Philosophy'), ('pdoc', 'Post Doc. - Post-doctorate')], max_length=7, unique=True),
        ),
        migrations.CreateModel(
            name='JointFacultyMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('entity_object_id', models.BigIntegerField()),
                ('designation', models.CharField(choices=[('af', 'Adjunct faculty'), ('ap', 'Assistant professor'), ('apc', 'Assistant professor (contract)'), ('aws', 'Assistant workshop superintendent'), ('asp', 'Associate professor'), ('cp', 'Chair professor'), ('cso', 'Chief scientific officer'), ('dif', 'DST INSPIRE faculty'), ('emf', 'Emeritus fellow'), ('ep', 'Emeritus professor'), ('ef', 'Ex faculty'), ('gf', 'Guest faculty'), ('hoc', 'Head of centre'), ('hod', 'Head of department'), ('jp', 'Joint professor'), ('lec', 'Lecturer'), ('pro', 'Professor'), ('raf', 'Ramanujan fellow'), ('rmf', 'Ramalingaswami fellow'), ('ref', 'Retired faculty'), ('so', 'Scientific officer'), ('sso', 'Senior scientific officer'), ('sp', 'System programmer'), ('vp', 'Visiting professor'), ('vs', 'Visiting scientist'), ('ws', 'Workshop superintendent')], max_length=3)),
                ('entity_content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'shell'), ('model', 'department')), models.Q(('app_label', 'shell'), ('model', 'centre')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JointFaculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('employee_id', models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator('\\d{6}')])),
                ('memberships', models.ManyToManyField(related_name='joint_faculty_members', to=settings.KERNEL_JOINTFACULTYMEMBERSHIP_MODEL)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.KERNEL_PERSON_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Joint Faculties',
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='jointfacultymembership',
            constraint=models.UniqueConstraint(fields=('entity_content_type', 'entity_object_id', 'designation'), name='unique_designation'),
        ),
    ]
