# Generated by Django 3.2 on 2022-05-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shell', '0008_auto_20220206_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='code',
            field=models.CharField(choices=[('azb', 'Azad bhawan'), ('ctb', 'Cautley bhawan'), ('gnb', 'Ganga bhawan'), ('gvb', 'Govind bhawan'), ('jlb', 'Jawahar bhawan'), ('mvb', 'Malviya bhawan'), ('rkb', 'Radhakrishnan bhawan'), ('rjb', 'Rajendra bhawan'), ('rgb', 'Rajiv bhawan'), ('rvb', 'Ravindra bhawan'), ('snb', 'Sarojini bhawan'), ('kgb', 'Kasturba bhawan'), ('igb', ' Indira bhawan'), ('vkg', 'Vigyan Kunj (girls)'), ('gph', 'G.P. hostel'), ('mrc', 'M.R. Chopra hostel'), ('azw', 'Azad wing'), ('dsb', 'D.S. Barrack hostel'), ('ank', 'A.N. Khosla house'), ('khs', 'Khosla international house (stay)'), ('ncn', 'N.C. Nigam house'), ('fah', 'Faculty home'), ('khg', 'Khosla international house (guest)'), ('vig', 'Vigyan kunj'), ('vik', 'Vikas nagar'), ('nit', 'Niti nagar'), ('jkh', 'Jai Krishna house'), ('shi', 'Shivalik apartments'), ('hva', 'Hill view apartments'), ('oth', "Old teachers' hostel"), ('far', 'Faculty residences'), ('doc', 'Doctoral residences'), ('nor', 'Non-resident')], max_length=3, unique=True),
        ),
    ]
