# Generated by Django 4.1.5 on 2023-09-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shell', '0010_alter_department_code_alter_residence_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre',
            name='code',
            field=models.CharField(choices=[('ahec', 'Alternate Hydro Energy Centre'), ('cnt', 'Centre for Nanotechnology'), ('caids', 'Centre for Aritificial Intelligence and Data Science'), ('cecqc', 'Continuing Education Centre and QIP Centre'), ('csst', 'Center for Space Science and Technology'), ('mfsdsai', 'Mehta Family School of Data Science and Artificial Intelligence'), ('cedmm', 'Centre of Excellence in Disaster Mitigation and Management'), ('cts', 'Centre for Transportation Systems'), ('chs', 'Centre for Himalayan Studies'), ('ceudm', 'Centre of Excellence in Urban Design and Management'), ('mgcl', 'Mahatma Gandhi Central Library'), ('cec', 'Continuing Education Centre'), ('icc', 'Institute Computer Centre'), ('iic', 'Institute Instrumentation Centre'), ('iprc', 'Intellectual Property Rights Cell'), ('etc', 'Education Technology Cell'), ('ih', 'Institute Hospital'), ('tides', 'Tides Incubation Centre')], max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='residence',
            name='code',
            field=models.CharField(choices=[('azb', 'Azad bhawan'), ('ctb', 'Cautley bhawan'), ('gnb', 'Ganga bhawan'), ('gvb', 'Govind bhawan'), ('jlb', 'Jawahar bhawan'), ('mvb', 'Malviya bhawan'), ('rkb', 'Radhakrishnan bhawan'), ('rjb', 'Rajendra bhawan'), ('rgb', 'Rajiv bhawan'), ('rvb', 'Ravindra bhawan'), ('hlb', 'Himalaya bhawan (boys)'), ('snb', 'Sarojini bhawan'), ('kgb', 'Kasturba bhawan'), ('igb', ' Indira bhawan'), ('vbg', 'Vigyan bhawan (girls)'), ('hia', 'Himgiri apartment'), ('hlg', 'Himalaya bhawan (girls)'), ('gph', 'G.P. hostel'), ('mrc', 'M.R. Chopra hostel'), ('azw', 'Azad wing'), ('dsb', 'D.S. Barrack hostel'), ('ank', 'A.N. Khosla house'), ('khs', 'Khosla international house (stay)'), ('mhs', 'Married hostel Saharanpur campus'), ('ncn', 'N.C. Nigam house'), ('fah', 'Faculty home'), ('khg', 'Khosla international house (guest)'), ('vib', 'Vigyan bhawan'), ('vik', 'Vikas nagar'), ('nit', 'Niti nagar'), ('jkh', 'Jai Krishna house'), ('shi', 'Shivalik apartments'), ('hva', 'Hill view apartments'), ('oth', "Old teachers' hostel"), ('far', 'Faculty residences'), ('doc', 'Doctoral residences'), ('nor', 'Non-resident')], max_length=3, unique=True),
        ),
    ]
