# Generated by Django 4.1.5 on 2024-04-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shell', '0011_alter_centre_code_alter_residence_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(choices=[('ased', 'Applied Science and Engineering Department'), ('amscd', 'Applied Mathematics and Scientific Computing Department'), ('arcd', 'Architecture and Planning Department'), ('btd', 'Biotechnology Department'), ('bsbed', 'Biosciences and Bioengineering Department'), ('ched', 'Chemical Engineering Department'), ('cyd', 'Chemistry Department'), ('ced', 'Civil Engineering Department'), ('csed', 'Computer Science and Engineering Department'), ('dd', 'Department of Design'), ('esd', 'Earth Sciences Department'), ('eqd', 'Earthquake Department'), ('eed', 'Electrical Engineering Department'), ('eced', 'Electronics and Communication Engineering Department'), ('hsd', 'Humanities and Social Sciences Department'), ('hyd', 'Hydrology Department'), ('hred', 'Hydro and Renewable Energy Department'), ('msd', 'Management Studies Department'), ('mad', 'Mathematics Department'), ('mied', 'Mechanical and Industrial Engineering Department'), ('mmed', 'Metallurgical and Materials Engineering Department'), ('ptd', 'Paper Technology Department'), ('phd', 'Physics Department'), ('pped', 'Polymer and Process Engineering Department'), ('wrdmd', 'Water Resources Development and Management Department'), ('qip', 'Quality Improvement Programme')], max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='facultymember',
            name='designation',
            field=models.CharField(choices=[('af', 'Adjunct faculty'), ('ap', 'Assistant professor'), ('apc', 'Assistant professor (contract)'), ('aws', 'Assistant workshop superintendent'), ('asp', 'Associate professor'), ('cp', 'Chair professor'), ('cso', 'Chief scientific officer'), ('dif', 'DST INSPIRE faculty'), ('emf', 'Emeritus fellow'), ('ep', 'Emeritus professor'), ('ef', 'Ex faculty'), ('gf', 'Guest faculty'), ('hoc', 'Head of centre'), ('hod', 'Head of department'), ('jp', 'Joint professor'), ('lec', 'Lecturer'), ('pro', 'Professor'), ('raf', 'Ramanujan fellow'), ('rmf', 'Ramalingaswami fellow'), ('ref', 'Retired faculty'), ('so', 'Scientific officer'), ('sso', 'Senior scientific officer'), ('sp', 'System programmer'), ('vp', 'Visiting professor'), ('vs', 'Visiting scientist'), ('ws', 'Workshop superintendent'), ('pop', 'Professor of practice'), ('ol', 'On Lien')], max_length=3),
        ),
        migrations.AlterField(
            model_name='jointfacultymembership',
            name='designation',
            field=models.CharField(choices=[('af', 'Adjunct faculty'), ('ap', 'Assistant professor'), ('apc', 'Assistant professor (contract)'), ('aws', 'Assistant workshop superintendent'), ('asp', 'Associate professor'), ('cp', 'Chair professor'), ('cso', 'Chief scientific officer'), ('dif', 'DST INSPIRE faculty'), ('emf', 'Emeritus fellow'), ('ep', 'Emeritus professor'), ('ef', 'Ex faculty'), ('gf', 'Guest faculty'), ('hoc', 'Head of centre'), ('hod', 'Head of department'), ('jp', 'Joint professor'), ('lec', 'Lecturer'), ('pro', 'Professor'), ('raf', 'Ramanujan fellow'), ('rmf', 'Ramalingaswami fellow'), ('ref', 'Retired faculty'), ('so', 'Scientific officer'), ('sso', 'Senior scientific officer'), ('sp', 'System programmer'), ('vp', 'Visiting professor'), ('vs', 'Visiting scientist'), ('ws', 'Workshop superintendent'), ('pop', 'Professor of practice'), ('ol', 'On Lien')], max_length=3),
        ),
    ]
